import http from 'node:http';import {readFile,writeFile,mkdir} from 'node:fs/promises';import {extname,resolve,normalize} from 'node:path';import {spawn} from 'node:child_process';import {buildPeriodData,reportPrompt} from './report-engine.mjs';import {analyzeWithFallback} from './analysis-provider.mjs';import {getConfig,addProduct,deleteProduct,setKeywords,pullRemoteConfig} from './config-store.mjs';
const port=Number(process.env.PORT||4173),root=resolve('.'),mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};let collection={running:false,exitCode:null};
const send=(res,status,data,type='application/json; charset=utf-8')=>{res.writeHead(status,{'Content-Type':type,'Access-Control-Allow-Origin':'*'});res.end(type.startsWith('application/json')?JSON.stringify(data):data)};async function body(req){let s='';for await(const c of req)s+=c;return JSON.parse(s||'{}')}
async function readProgress(){try{return JSON.parse(await readFile('data/collection-progress.json','utf8'))}catch{return null}}
async function saveReport(report){await mkdir('public/data',{recursive:true});let reports=[];try{reports=JSON.parse(await readFile('public/data/reports.json','utf8'))}catch{}reports.unshift(report);await writeFile('public/data/reports.json',JSON.stringify(reports.slice(0,100),null,2))}
function startCollection(){if(collection.running)return false;collection={running:true,startedAt:new Date().toISOString(),exitCode:null,output:''};const child=spawn(process.execPath,['--env-file-if-exists=.env.local','run-collection.mjs'],{cwd:root,windowsHide:true});child.stdout.on('data',d=>collection.output=(collection.output+d).slice(-20000));child.stderr.on('data',d=>collection.output=(collection.output+d).slice(-20000));child.on('error',e=>{collection.error=e.message;collection.running=false});child.on('close',code=>{collection.exitCode=code;collection.running=false;collection.finishedAt=new Date().toISOString()});return true}
const server=http.createServer(async(req,res)=>{try{
 if(req.method==='GET'&&req.url==='/api/config')return send(res,200,await getConfig());
 if(req.method==='POST'&&req.url==='/api/products'){const x=await body(req);return send(res,200,x.action==='delete'?await deleteProduct(x.asin):await addProduct(x))}
 if(req.method==='POST'&&req.url==='/api/keywords'){return send(res,200,await setKeywords(await body(req)))}
 if(req.method==='POST'&&req.url==='/api/collect'){const started=startCollection();return send(res,started?202:409,{started,status:collection})}
 if(req.method==='GET'&&req.url==='/api/collect/status')return send(res,200,{...collection,progress:await readProgress()});
 if(req.method==='POST'&&req.url==='/api/report'){const x=await body(req),days=[7,15,30].includes(Number(x.days))?Number(x.days):7;if(!/^[A-Z0-9]{10}$/.test(String(x.asin||'')))return send(res,400,{error:'invalid_asin'});const data=buildPeriodData(x.asin,days);if(!data.product.last)return send(res,404,{error:'no_snapshot_data'});const order={auto:'codex,deepseek,openai',codex:'codex',deepseek:'deepseek',openai:'openai'}[x.provider]||'codex,deepseek,openai',result=await analyzeWithFallback(reportPrompt(data),{providerOrder:order}),report={id:`period-${x.asin}-${Date.now()}`,type:'period',asin:x.asin,days,createdAt:new Date().toISOString(),provider:result.provider,analysis:result.text,data,attempts:result.attempts};await saveReport(report);return send(res,200,report)}
 const pathname=req.url==='/'?'/index.html':decodeURIComponent(req.url.split('?')[0]),file=resolve(root,'.'+normalize(pathname));if(!file.startsWith(root))return send(res,403,{error:'forbidden'});const ext=extname(file),type=mime[ext]||'application/octet-stream',content=await readFile(file);res.writeHead(200,{'Content-Type':type,'Access-Control-Allow-Origin':'*'});return res.end(content)
}catch(e){send(res,e.code==='ENOENT'?404:400,{error:e.message})}});
pullRemoteConfig().then(()=>console.log('Config synced from remote API')).catch(()=>{});
server.listen(port,'127.0.0.1',()=>console.log(`ASIN Radar: http://127.0.0.1:${port}`));
